import type { Sunglasses } from "./types";

/**
 * Mock data for the scaffold. The real system will scrape the pasted URL and a
 * live retailer index; for now we resolve a plausible "source" product from the
 * URL's keywords and match it against a fixed CATALOG of cheaper alternatives.
 *
 * `imageUrl` is intentionally left blank — the UI renders an on-brand SVG
 * illustration (see components/common/product-image.tsx) so the demo never
 * shows a broken image. Swap in real images later without touching the matcher.
 */

/** Premium reference products a pasted URL can resolve to. */
export const SOURCES: Sunglasses[] = [
  {
    id: "src-rayban-wayfarer",
    brand: "Ray-Ban",
    model: "Original Wayfarer Classic",
    retailer: "ray-ban.com",
    productUrl: "https://www.ray-ban.com/usa/sunglasses/RB2140",
    imageUrl: "",
    price: 171,
    currency: "USD",
    shape: "wayfarer",
    frameMaterial: "acetate",
    lensMaterial: "glass",
    lensWidthMm: 50,
    bridgeMm: 22,
    templeMm: 150,
    polarized: false,
    uvProtection: "UV400",
    color: "Black",
    fit: "medium",
    blurb: "The icon. Heavy acetate, crystal lenses, unmistakable silhouette.",
  },
  {
    id: "src-oakley-holbrook",
    brand: "Oakley",
    model: "Holbrook",
    retailer: "oakley.com",
    productUrl: "https://www.oakley.com/en-us/product/W0OO9102",
    imageUrl: "",
    price: 173,
    currency: "USD",
    shape: "square",
    frameMaterial: "injected",
    lensMaterial: "polycarbonate",
    lensWidthMm: 55,
    bridgeMm: 18,
    templeMm: 137,
    polarized: true,
    uvProtection: "UV400",
    color: "Matte Black / Prizm",
    fit: "medium",
    blurb: "Sport-heritage square frame with Prizm polarized lenses.",
  },
  {
    id: "src-persol-649",
    brand: "Persol",
    model: "649 Original",
    retailer: "persol.com",
    productUrl: "https://www.persol.com/usa/0PO0649",
    imageUrl: "",
    price: 280,
    currency: "USD",
    shape: "square",
    frameMaterial: "acetate",
    lensMaterial: "glass",
    lensWidthMm: 54,
    bridgeMm: 20,
    templeMm: 145,
    polarized: true,
    uvProtection: "UV400",
    color: "Havana",
    fit: "wide",
    blurb: "Hand-made Italian acetate with the signature arrow temples.",
  },
  {
    id: "src-rayban-aviator",
    brand: "Ray-Ban",
    model: "Aviator Classic",
    retailer: "ray-ban.com",
    productUrl: "https://www.ray-ban.com/usa/sunglasses/RB3025",
    imageUrl: "",
    price: 178,
    currency: "USD",
    shape: "aviator",
    frameMaterial: "metal",
    lensMaterial: "glass",
    lensWidthMm: 58,
    bridgeMm: 14,
    templeMm: 135,
    polarized: false,
    uvProtection: "UV400",
    color: "Gold / Green G-15",
    fit: "medium",
    blurb: "The teardrop aviator that started it all.",
  },
];

/** Cheaper alternatives the matcher scores against the source. */
export const CATALOG: Sunglasses[] = [
  {
    id: "cat-knockaround-premium",
    brand: "Knockaround",
    model: "Premiums",
    retailer: "knockaround.com",
    productUrl: "https://knockaround.com/products/premiums",
    imageUrl: "",
    price: 28,
    currency: "USD",
    shape: "wayfarer",
    frameMaterial: "injected",
    lensMaterial: "polycarbonate",
    lensWidthMm: 51,
    bridgeMm: 21,
    templeMm: 148,
    polarized: true,
    uvProtection: "UV400",
    color: "Black on Black",
    fit: "medium",
    blurb: "Cult-favorite wayfarer with polarized lenses for under $30.",
  },
  {
    id: "cat-sungait-classic",
    brand: "SUNGAIT",
    model: "Vintage Classic",
    retailer: "amazon.com",
    productUrl: "https://www.amazon.com/dp/B01N5RD4HF",
    imageUrl: "",
    price: 18,
    currency: "USD",
    shape: "wayfarer",
    frameMaterial: "tr90",
    lensMaterial: "polycarbonate",
    lensWidthMm: 50,
    bridgeMm: 20,
    templeMm: 145,
    polarized: true,
    uvProtection: "UV400",
    color: "Black Frame / Grey Lens",
    fit: "medium",
    blurb: "Lightweight TR90 wayfarer, the perennial budget best-seller.",
  },
  {
    id: "cat-warby-haskell",
    brand: "Warby Parker",
    model: "Haskell",
    retailer: "warbyparker.com",
    productUrl: "https://www.warbyparker.com/sunglasses/haskell",
    imageUrl: "",
    price: 95,
    currency: "USD",
    shape: "wayfarer",
    frameMaterial: "acetate",
    lensMaterial: "cr39",
    lensWidthMm: 52,
    bridgeMm: 20,
    templeMm: 145,
    polarized: true,
    uvProtection: "UV400",
    color: "Jet Black",
    fit: "medium",
    blurb: "Custom Italian acetate, polarized, with a clean square-wayfarer line.",
  },
  {
    id: "cat-privrevaux-heir",
    brand: "Privé Revaux",
    model: "The Heir",
    retailer: "priverevaux.com",
    productUrl: "https://www.priverevaux.com/products/the-heir",
    imageUrl: "",
    price: 30,
    currency: "USD",
    shape: "wayfarer",
    frameMaterial: "acetate",
    lensMaterial: "polycarbonate",
    lensWidthMm: 49,
    bridgeMm: 21,
    templeMm: 147,
    polarized: true,
    uvProtection: "UV400",
    color: "Caviar Black",
    fit: "medium",
    blurb: "Polarized acetate wayfarer with a celebrity-backed price.",
  },
  {
    id: "cat-goodr-og",
    brand: "goodr",
    model: "OG",
    retailer: "goodr.com",
    productUrl: "https://www.goodr.com/products/the-og",
    imageUrl: "",
    price: 25,
    currency: "USD",
    shape: "square",
    frameMaterial: "tr90",
    lensMaterial: "polycarbonate",
    lensWidthMm: 53,
    bridgeMm: 17,
    templeMm: 138,
    polarized: true,
    uvProtection: "UV400",
    color: "A Ginger's Soul",
    fit: "medium",
    blurb: "No-slip, no-bounce polarized sport-casual frame.",
  },
  {
    id: "cat-torege-sport",
    brand: "TOREGE",
    model: "Tr90 Sports",
    retailer: "amazon.com",
    productUrl: "https://www.amazon.com/dp/B07K2Vprint",
    imageUrl: "",
    price: 22,
    currency: "USD",
    shape: "sport",
    frameMaterial: "tr90",
    lensMaterial: "polycarbonate",
    lensWidthMm: 56,
    bridgeMm: 16,
    templeMm: 135,
    polarized: true,
    uvProtection: "UV400",
    color: "Black / Revo Red",
    fit: "wide",
    blurb: "Wraparound sport frame with interchangeable polarized lenses.",
  },
  {
    id: "cat-duduma-polarized",
    brand: "Duduma",
    model: "Polarized Sports",
    retailer: "amazon.com",
    productUrl: "https://www.amazon.com/dp/B00OT3ARTW",
    imageUrl: "",
    price: 20,
    currency: "USD",
    shape: "sport",
    frameMaterial: "tr90",
    lensMaterial: "polycarbonate",
    lensWidthMm: 57,
    bridgeMm: 17,
    templeMm: 136,
    polarized: true,
    uvProtection: "UV400",
    color: "Black / Blue",
    fit: "wide",
    blurb: "Best-selling wraparound sport shield for cycling & running.",
  },
  {
    id: "cat-zenni-aviator",
    brand: "Zenni",
    model: "Metal Aviator",
    retailer: "zennioptical.com",
    productUrl: "https://www.zennioptical.com/aviator-sunglasses",
    imageUrl: "",
    price: 24,
    currency: "USD",
    shape: "aviator",
    frameMaterial: "metal",
    lensMaterial: "polycarbonate",
    lensWidthMm: 58,
    bridgeMm: 14,
    templeMm: 138,
    polarized: true,
    uvProtection: "UV400",
    color: "Gold / Green",
    fit: "medium",
    blurb: "Classic teardrop aviator with polarized tint, made-to-order.",
  },
  {
    id: "cat-eyebuydirect-flight",
    brand: "EyeBuyDirect",
    model: "Flight",
    retailer: "eyebuydirect.com",
    productUrl: "https://www.eyebuydirect.com/sunglasses/flight",
    imageUrl: "",
    price: 38,
    currency: "USD",
    shape: "aviator",
    frameMaterial: "metal",
    lensMaterial: "cr39",
    lensWidthMm: 57,
    bridgeMm: 15,
    templeMm: 140,
    polarized: false,
    uvProtection: "UV400",
    color: "Gold",
    fit: "medium",
    blurb: "Double-bridge aviator with a thin metal frame and tinted lenses.",
  },
  {
    id: "cat-sojos-aviator",
    brand: "SOJOS",
    model: "Classic Aviator",
    retailer: "amazon.com",
    productUrl: "https://www.amazon.com/dp/B071XCZ3CL",
    imageUrl: "",
    price: 16,
    currency: "USD",
    shape: "aviator",
    frameMaterial: "metal",
    lensMaterial: "polycarbonate",
    lensWidthMm: 59,
    bridgeMm: 14,
    templeMm: 135,
    polarized: false,
    uvProtection: "UV400",
    color: "Silver / Grey",
    fit: "medium",
    blurb: "Oversized metal aviator that punches well above its price.",
  },
  {
    id: "cat-quay-x",
    brand: "Quay",
    model: "On The Prowl",
    retailer: "quayaustralia.com",
    productUrl: "https://www.quayaustralia.com/products/on-the-prowl",
    imageUrl: "",
    price: 60,
    currency: "USD",
    shape: "square",
    frameMaterial: "injected",
    lensMaterial: "polycarbonate",
    lensWidthMm: 54,
    bridgeMm: 19,
    templeMm: 142,
    polarized: true,
    uvProtection: "UV400",
    color: "Black",
    fit: "wide",
    blurb: "Bold oversized square with a polarized smoke lens.",
  },
  {
    id: "cat-lespecs-bandwagon",
    brand: "Le Specs",
    model: "Bandwagon",
    retailer: "lespecs.com",
    productUrl: "https://www.lespecs.com/products/bandwagon",
    imageUrl: "",
    price: 69,
    currency: "USD",
    shape: "square",
    frameMaterial: "acetate",
    lensMaterial: "cr39",
    lensWidthMm: 53,
    bridgeMm: 21,
    templeMm: 140,
    polarized: false,
    uvProtection: "UV400",
    color: "Black Rubber",
    fit: "medium",
    blurb: "Australian-designed keyhole square with a matte finish.",
  },
  {
    id: "cat-komono-vivien",
    brand: "Komono",
    model: "Vivien",
    retailer: "komono.com",
    productUrl: "https://www.komono.com/products/vivien",
    imageUrl: "",
    price: 79,
    currency: "USD",
    shape: "cat-eye",
    frameMaterial: "acetate",
    lensMaterial: "cr39",
    lensWidthMm: 52,
    bridgeMm: 20,
    templeMm: 142,
    polarized: false,
    uvProtection: "UV400",
    color: "Tortoise",
    fit: "medium",
    blurb: "Refined cat-eye in hand-polished acetate.",
  },
  {
    id: "cat-hawkers-classic",
    brand: "Hawkers",
    model: "Classic Six",
    retailer: "hawkersco.com",
    productUrl: "https://www.hawkersco.com/products/classic-six",
    imageUrl: "",
    price: 35,
    currency: "USD",
    shape: "round",
    frameMaterial: "tr90",
    lensMaterial: "polycarbonate",
    lensWidthMm: 48,
    bridgeMm: 21,
    templeMm: 145,
    polarized: false,
    uvProtection: "UV400",
    color: "Black / Dark",
    fit: "narrow",
    blurb: "Spanish-designed round frame with a flat-top brow.",
  },
  {
    id: "cat-roka-rory",
    brand: "ROKA",
    model: "Rory",
    retailer: "roka.com",
    productUrl: "https://www.roka.com/products/rory",
    imageUrl: "",
    price: 135,
    currency: "USD",
    shape: "square",
    frameMaterial: "titanium",
    lensMaterial: "nylon",
    lensWidthMm: 54,
    bridgeMm: 18,
    templeMm: 140,
    polarized: true,
    uvProtection: "UV400",
    color: "Matte Black",
    fit: "medium",
    blurb: "Titanium core, featherweight, with grippy no-slip arms.",
  },
  {
    id: "cat-sungod-renegades",
    brand: "SunGod",
    model: "Renegades",
    retailer: "sungod.co",
    productUrl: "https://www.sungod.co/sunglasses/renegades",
    imageUrl: "",
    price: 70,
    currency: "USD",
    shape: "wayfarer",
    frameMaterial: "injected",
    lensMaterial: "nylon",
    lensWidthMm: 51,
    bridgeMm: 20,
    templeMm: 145,
    polarized: true,
    uvProtection: "UV400",
    color: "Black / Smoke",
    fit: "medium",
    blurb: "Customisable, recycled-frame all-rounder with polarized 8KO lenses.",
  },
];

/**
 * Resolve a plausible source product from a pasted URL by keyword-matching the
 * brand/model. Falls back to the Wayfarer so the demo always has a source.
 */
export function resolveSource(url: string): Sunglasses {
  const haystack = url.toLowerCase();
  const keyed: Array<[string[], string]> = [
    [["holbrook", "oakley"], "src-oakley-holbrook"],
    [["aviator", "rb3025", "3025"], "src-rayban-aviator"],
    [["persol", "649"], "src-persol-649"],
    [["wayfarer", "rayban", "ray-ban", "rb2140", "2140"], "src-rayban-wayfarer"],
  ];
  for (const [needles, id] of keyed) {
    if (needles.some((n) => haystack.includes(n))) {
      const found = SOURCES.find((s) => s.id === id);
      if (found) return found;
    }
  }
  return SOURCES[0];
}
