"""Mock catalog + source resolution — mirrors src/lib/mock-data.ts."""

from __future__ import annotations

from models import Sunglasses

SOURCES: list[Sunglasses] = [
    Sunglasses(
        id="src-rayban-wayfarer", brand="Ray-Ban",
        model="Original Wayfarer Classic", retailer="ray-ban.com",
        productUrl="https://www.ray-ban.com/usa/sunglasses/RB2140",
        price=171, shape="wayfarer", frameMaterial="acetate", lensMaterial="glass",
        lensWidthMm=50, bridgeMm=22, templeMm=150, polarized=False,
        uvProtection="UV400", color="Black", fit="medium",
        blurb="The icon. Heavy acetate, crystal lenses, unmistakable silhouette.",
    ),
    Sunglasses(
        id="src-oakley-holbrook", brand="Oakley", model="Holbrook",
        retailer="oakley.com",
        productUrl="https://www.oakley.com/en-us/product/W0OO9102",
        price=173, shape="square", frameMaterial="injected",
        lensMaterial="polycarbonate", lensWidthMm=55, bridgeMm=18, templeMm=137,
        polarized=True, uvProtection="UV400", color="Matte Black / Prizm",
        fit="medium",
        blurb="Sport-heritage square frame with Prizm polarized lenses.",
    ),
    Sunglasses(
        id="src-persol-649", brand="Persol", model="649 Original",
        retailer="persol.com", productUrl="https://www.persol.com/usa/0PO0649",
        price=280, shape="square", frameMaterial="acetate", lensMaterial="glass",
        lensWidthMm=54, bridgeMm=20, templeMm=145, polarized=True,
        uvProtection="UV400", color="Havana", fit="wide",
        blurb="Hand-made Italian acetate with the signature arrow temples.",
    ),
    Sunglasses(
        id="src-rayban-aviator", brand="Ray-Ban", model="Aviator Classic",
        retailer="ray-ban.com",
        productUrl="https://www.ray-ban.com/usa/sunglasses/RB3025",
        price=178, shape="aviator", frameMaterial="metal", lensMaterial="glass",
        lensWidthMm=58, bridgeMm=14, templeMm=135, polarized=False,
        uvProtection="UV400", color="Gold / Green G-15", fit="medium",
        blurb="The teardrop aviator that started it all.",
    ),
]

CATALOG: list[Sunglasses] = [
    Sunglasses(id="cat-knockaround-premium", brand="Knockaround", model="Premiums",
        retailer="knockaround.com", productUrl="https://knockaround.com/products/premiums",
        price=28, shape="wayfarer", frameMaterial="injected", lensMaterial="polycarbonate",
        lensWidthMm=51, bridgeMm=21, templeMm=148, polarized=True, uvProtection="UV400",
        color="Black on Black", fit="medium",
        blurb="Cult-favorite wayfarer with polarized lenses for under $30."),
    Sunglasses(id="cat-sungait-classic", brand="SUNGAIT", model="Vintage Classic",
        retailer="amazon.com", productUrl="https://www.amazon.com/dp/B01N5RD4HF",
        price=18, shape="wayfarer", frameMaterial="tr90", lensMaterial="polycarbonate",
        lensWidthMm=50, bridgeMm=20, templeMm=145, polarized=True, uvProtection="UV400",
        color="Black Frame / Grey Lens", fit="medium",
        blurb="Lightweight TR90 wayfarer, the perennial budget best-seller."),
    Sunglasses(id="cat-warby-haskell", brand="Warby Parker", model="Haskell",
        retailer="warbyparker.com", productUrl="https://www.warbyparker.com/sunglasses/haskell",
        price=95, shape="wayfarer", frameMaterial="acetate", lensMaterial="cr39",
        lensWidthMm=52, bridgeMm=20, templeMm=145, polarized=True, uvProtection="UV400",
        color="Jet Black", fit="medium",
        blurb="Custom Italian acetate, polarized, with a clean square-wayfarer line."),
    Sunglasses(id="cat-privrevaux-heir", brand="Privé Revaux", model="The Heir",
        retailer="priverevaux.com", productUrl="https://www.priverevaux.com/products/the-heir",
        price=30, shape="wayfarer", frameMaterial="acetate", lensMaterial="polycarbonate",
        lensWidthMm=49, bridgeMm=21, templeMm=147, polarized=True, uvProtection="UV400",
        color="Caviar Black", fit="medium",
        blurb="Polarized acetate wayfarer with a celebrity-backed price."),
    Sunglasses(id="cat-goodr-og", brand="goodr", model="OG", retailer="goodr.com",
        productUrl="https://www.goodr.com/products/the-og",
        price=25, shape="square", frameMaterial="tr90", lensMaterial="polycarbonate",
        lensWidthMm=53, bridgeMm=17, templeMm=138, polarized=True, uvProtection="UV400",
        color="A Ginger's Soul", fit="medium",
        blurb="No-slip, no-bounce polarized sport-casual frame."),
    Sunglasses(id="cat-torege-sport", brand="TOREGE", model="Tr90 Sports",
        retailer="amazon.com", productUrl="https://www.amazon.com/dp/B07K2Vprint",
        price=22, shape="sport", frameMaterial="tr90", lensMaterial="polycarbonate",
        lensWidthMm=56, bridgeMm=16, templeMm=135, polarized=True, uvProtection="UV400",
        color="Black / Revo Red", fit="wide",
        blurb="Wraparound sport frame with interchangeable polarized lenses."),
    Sunglasses(id="cat-duduma-polarized", brand="Duduma", model="Polarized Sports",
        retailer="amazon.com", productUrl="https://www.amazon.com/dp/B00OT3ARTW",
        price=20, shape="sport", frameMaterial="tr90", lensMaterial="polycarbonate",
        lensWidthMm=57, bridgeMm=17, templeMm=136, polarized=True, uvProtection="UV400",
        color="Black / Blue", fit="wide",
        blurb="Best-selling wraparound sport shield for cycling & running."),
    Sunglasses(id="cat-zenni-aviator", brand="Zenni", model="Metal Aviator",
        retailer="zennioptical.com", productUrl="https://www.zennioptical.com/aviator-sunglasses",
        price=24, shape="aviator", frameMaterial="metal", lensMaterial="polycarbonate",
        lensWidthMm=58, bridgeMm=14, templeMm=138, polarized=True, uvProtection="UV400",
        color="Gold / Green", fit="medium",
        blurb="Classic teardrop aviator with polarized tint, made-to-order."),
    Sunglasses(id="cat-eyebuydirect-flight", brand="EyeBuyDirect", model="Flight",
        retailer="eyebuydirect.com", productUrl="https://www.eyebuydirect.com/sunglasses/flight",
        price=38, shape="aviator", frameMaterial="metal", lensMaterial="cr39",
        lensWidthMm=57, bridgeMm=15, templeMm=140, polarized=False, uvProtection="UV400",
        color="Gold", fit="medium",
        blurb="Double-bridge aviator with a thin metal frame and tinted lenses."),
    Sunglasses(id="cat-sojos-aviator", brand="SOJOS", model="Classic Aviator",
        retailer="amazon.com", productUrl="https://www.amazon.com/dp/B071XCZ3CL",
        price=16, shape="aviator", frameMaterial="metal", lensMaterial="polycarbonate",
        lensWidthMm=59, bridgeMm=14, templeMm=135, polarized=False, uvProtection="UV400",
        color="Silver / Grey", fit="medium",
        blurb="Oversized metal aviator that punches well above its price."),
    Sunglasses(id="cat-quay-x", brand="Quay", model="On The Prowl",
        retailer="quayaustralia.com", productUrl="https://www.quayaustralia.com/products/on-the-prowl",
        price=60, shape="square", frameMaterial="injected", lensMaterial="polycarbonate",
        lensWidthMm=54, bridgeMm=19, templeMm=142, polarized=True, uvProtection="UV400",
        color="Black", fit="wide",
        blurb="Bold oversized square with a polarized smoke lens."),
    Sunglasses(id="cat-lespecs-bandwagon", brand="Le Specs", model="Bandwagon",
        retailer="lespecs.com", productUrl="https://www.lespecs.com/products/bandwagon",
        price=69, shape="square", frameMaterial="acetate", lensMaterial="cr39",
        lensWidthMm=53, bridgeMm=21, templeMm=140, polarized=False, uvProtection="UV400",
        color="Black Rubber", fit="medium",
        blurb="Australian-designed keyhole square with a matte finish."),
    Sunglasses(id="cat-komono-vivien", brand="Komono", model="Vivien",
        retailer="komono.com", productUrl="https://www.komono.com/products/vivien",
        price=79, shape="cat-eye", frameMaterial="acetate", lensMaterial="cr39",
        lensWidthMm=52, bridgeMm=20, templeMm=142, polarized=False, uvProtection="UV400",
        color="Tortoise", fit="medium",
        blurb="Refined cat-eye in hand-polished acetate."),
    Sunglasses(id="cat-hawkers-classic", brand="Hawkers", model="Classic Six",
        retailer="hawkersco.com", productUrl="https://www.hawkersco.com/products/classic-six",
        price=35, shape="round", frameMaterial="tr90", lensMaterial="polycarbonate",
        lensWidthMm=48, bridgeMm=21, templeMm=145, polarized=False, uvProtection="UV400",
        color="Black / Dark", fit="narrow",
        blurb="Spanish-designed round frame with a flat-top brow."),
    Sunglasses(id="cat-roka-rory", brand="ROKA", model="Rory", retailer="roka.com",
        productUrl="https://www.roka.com/products/rory",
        price=135, shape="square", frameMaterial="titanium", lensMaterial="nylon",
        lensWidthMm=54, bridgeMm=18, templeMm=140, polarized=True, uvProtection="UV400",
        color="Matte Black", fit="medium",
        blurb="Titanium core, featherweight, with grippy no-slip arms."),
    Sunglasses(id="cat-sungod-renegades", brand="SunGod", model="Renegades",
        retailer="sungod.co", productUrl="https://www.sungod.co/sunglasses/renegades",
        price=70, shape="wayfarer", frameMaterial="injected", lensMaterial="nylon",
        lensWidthMm=51, bridgeMm=20, templeMm=145, polarized=True, uvProtection="UV400",
        color="Black / Smoke", fit="medium",
        blurb="Customisable, recycled-frame all-rounder with polarized 8KO lenses."),
]

_KEYED: list[tuple[list[str], str]] = [
    (["holbrook", "oakley"], "src-oakley-holbrook"),
    (["aviator", "rb3025", "3025"], "src-rayban-aviator"),
    (["persol", "649"], "src-persol-649"),
    (["wayfarer", "rayban", "ray-ban", "rb2140", "2140"], "src-rayban-wayfarer"),
]


def resolve_source(url: str) -> Sunglasses:
    """Resolve a plausible source product from a pasted URL's keywords."""
    haystack = url.lower()
    for needles, source_id in _KEYED:
        if any(n in haystack for n in needles):
            for s in SOURCES:
                if s.id == source_id:
                    return s
    return SOURCES[0]
